In [ ]:
!pip install -U pip wheel setuptools
!pip install concrete-ml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.0/804.0 kB 12.4 MB/s eta 0:00:00
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.7.2
    Uninstalling setuptools-67.7.2:
      Successfully uninstalled setuptools-67.7.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.1/178.1 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.9/135.9 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.3/357.3 kB 18.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 MB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.6/164.6 kB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 59.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 55.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 671.6/671.6 kB 50.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 74.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

from concrete.ml.sklearn.rf import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier as skRF

import time
import pandas as pd
import numpy as np
from numpy import mean
from numpy import std


In [ ]:
# Reading the dataset
dataset = pd.read_csv("gdrive/MyDrive/Special-Problem-Colab/Brain_GSE50161.csv")
dataset.head()

samples        type  1007_s_at   1053_at     117_at    121_at  1255_g_at  \
0      834  ependymoma  12.498150  7.604868   6.880934  9.027128   4.176175   
1      835  ependymoma  13.067436  7.998090   7.209076  9.723322   4.826126   
2      836  ependymoma  13.068179  8.573674   8.647684  9.613002   4.396581   
3      837  ependymoma  12.456040  9.098977   6.628784  8.517677   4.154847   
4      838  ependymoma  12.699958  8.800721  11.556188  9.166309   4.165891   

    1294_at   1316_at   1320_at  ...  AFFX-r2-Ec-bioD-3_at  \
0  7.224920  6.085942  6.835999  ...              9.979005   
1  7.539381  6.250962  8.012549  ...             11.924749   
2  7.813101  6.007746  7.178156  ...             12.154405   
3  8.361843  6.596064  6.347285  ...             11.969072   
4  7.923826  6.212754  6.866387  ...             11.411701   

   AFFX-r2-Ec-bioD-5_at  AFFX-r2-P1-cre-3_at  AFFX-r2-P1-cre-5_at  \
0              9.926470            12.719785            12.777792   
1             11.215930            13.605662            13.401342   
2             11.532460            13.764593            13.477800   
3             11.288801            13.600828            13.379029   
4             11.169317            13.751442            13.803646   

   AFFX-ThrX-3_at  AFFX-ThrX-5_at  AFFX-ThrX-M_at  AFFX-TrpnX-3_at  \
0        5.403657        4.870548        4.047380         3.721936   
1        5.224555        4.895315        3.786437         3.564481   
2        5.303565        5.052184        4.005343         3.595382   
3        4.953429        4.708371        3.892318         3.759429   
4        4.892677        4.773806        3.796856         3.577544   

   AFFX-TrpnX-5_at  AFFX-TrpnX-M_at  
0         4.516434         4.749940  
1         4.430891         4.491416  
2         4.563494         4.668827  
3         4.748381         4.521275  
4         4.504385         4.541450  

[5 rows x 54677 columns]

In [ ]:
feature_cols = [c for c in dataset.columns[2:]]
x = dataset.loc[:,feature_cols].values #must be floats
y = dataset.loc[:,'type'].values #must be integers

In [ ]:
# Preprocessing with labels for the lineage
le = preprocessing.LabelEncoder()
y = le.fit_transform(y)
le_mapping = dict(zip(le.classes_, range(len(le.classes_))))
print(le_mapping)
# print(y)

# x = x.astype(float)
# print(x)
# print("done!", x.shape)

{'ependymoma': 0, 'glioblastoma': 1, 'medulloblastoma': 2, 'normal': 3, 'pilocytic_astrocytoma': 4}


In [ ]:
# Feature Selection

from sklearn.feature_selection import SelectKBest, chi2

print("\nUsing K best features feature selection...")
print("Shape of x before selection: ", x.shape)
selector = SelectKBest(chi2, k = 20)
x_new = selector.fit_transform(x, y)
x = x_new
print("Shape of x after selection: ", x.shape)
print("\n", x)



Using K best features feature selection...
Shape of x before selection:  (130, 54675)
Shape of x after selection:  (130, 20)

 [[10.72479043  7.97994703  4.61166708 ...  4.17375617 10.35812997
   3.64268   ]
 [ 9.34955227  6.45471699  3.91932265 ...  3.60306914  9.2568473
   3.57011652]
 [ 9.63113411  8.07929017  3.90347265 ...  3.67253827  8.8045389
   3.66697249]
 ...
 [ 5.54149779  4.80014429  3.91737545 ...  4.23060314  5.93035769
   3.74996298]
 [ 5.02986445  3.15203731  4.31564541 ...  3.5515603   5.13432725
   3.68967281]
 [ 4.94076803  4.08426419  3.90425321 ...  3.78264203  5.123375
   3.83489158]]


In [ ]:
# Get most important features accorting to Kbest

cols_index = selector.get_support(indices=True)
most_important_features = []

print("\nSelected features: ")
for col in cols_index:
  most_important_features.append(str(feature_cols[col]))
print(most_important_features)

print("\n")
print(dataset[most_important_features])


Selected features: 
['1553635_s_at', '1557636_a_at', '1568612_at', '203001_s_at', '206135_at', '206282_at', '206502_s_at', '210016_at', '210033_s_at', '221805_at', '227242_s_at', '229012_at', '231077_at', '231731_at', '236085_at', '237282_s_at', '240065_at', '242128_at', '242162_at', '244118_at']


     1553635_s_at  1557636_a_at  1568612_at  203001_s_at  206135_at  \
0       10.724790      7.979947    4.611667     6.176408   5.115718   
1        9.349552      6.454717    3.919323     8.043318   6.787502   
2        9.631134      8.079290    3.903473     6.977734   4.522126   
3       11.010364      9.757430    8.223931     9.552097   4.452334   
4        9.862121      8.762606    3.816280     7.255989   5.292506   
..            ...           ...         ...          ...        ...   
125      5.139725      4.153775    5.061523     7.345922   5.450018   
126      5.462156      3.981230    4.093496    10.998515   5.555544   
127      5.541498      4.800144    3.917375     9.580355   5

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.10)

print(f"training set size: {X_train.shape[0]}")
print(f"testing set size: {X_test.shape[0]}")

training set size: 117
testing set size: 13


In [ ]:
# RandomForest
skmodel = skRF(class_weight='balanced')
start_time = time.time()
skmodel.fit(X_train,y_train)
print(f"Running time for sklearn training is {time.time() - start_time} seconds")
start_time = time.time()
y_pred_clear = skmodel.predict(X_test)
print(f"Running time for sklearn prediction is {time.time() - start_time} seconds")


quant = RandomForestClassifier(class_weight='balanced')
start_time = time.time()
quant.fit(X_train, y_train)
print(f"Running time for quantized plaintext training is {time.time() - start_time} seconds")
start_time = time.time()
y_pred_q = quant.predict(X_test)
print(f"Running time for quantized plaintext prediction is {time.time() - start_time} seconds")

print("\n Random Forest Results \n")

# Accuracy
sk_accuracy = accuracy_score(y_test, y_pred_clear) * 100
quant_accuracy = accuracy_score(y_test, y_pred_q) * 100
print(f"Sklearn accuracy: {sk_accuracy:.4f}")
print(f"Quantized Clear Accuracy: {quant_accuracy:.4f}")

# Balanced Accuracy
sk_bal_accuracy = balanced_accuracy_score(y_test, y_pred_clear) * 100
quant_bal_accuracy = balanced_accuracy_score(y_test, y_pred_q) * 100
print(f"Sklearn Balanced accuracy: {sk_bal_accuracy:.4f}")
print(f"Quantized Clear Balanced Accuracy: {quant_bal_accuracy:.4f}")

# F1 Score
sk_f1 = f1_score(y_test, y_pred_clear, average='weighted') * 100
quant_f1 = f1_score(y_test, y_pred_q, average='weighted') * 100
print(f"Sklearn F1 Score: {sk_f1:.4f}")
print(f"Quantized Clear F1 Score: {quant_f1:.4f}")

# Recall / Sensitivity Score
sk_recall = recall_score(y_test, y_pred_clear, average='weighted') * 100
quant_recall = recall_score(y_test, y_pred_q, average='weighted') * 100
print(f"Sklearn Recall Score: {sk_recall:.4f}")
print(f"Quantized Clear Recall Score: {quant_recall:.4f}")

print("\n")
print("SKLEARN PREDICTION:\n", y_pred_clear)
print("QUANTIZED CLEAR PREDICTION:\n", y_pred_q)
print("ACTUAL:\n", y_test)

Running time for sklearn training is 0.29044437408447266 seconds
Running time for sklearn prediction is 0.02879500389099121 seconds
Running time for quantized plaintext training is 0.27140188217163086 seconds
Running time for quantized plaintext prediction is 0.00436091423034668 seconds

 Random Forest Results 

Sklearn accuracy: 84.6154
Quantized Clear Accuracy: 92.3077
Sklearn Balanced accuracy: 85.4167
Quantized Clear Balanced Accuracy: 93.7500
Sklearn F1 Score: 84.4156
Quantized Clear F1 Score: 92.3077
Sklearn Recall Score: 84.6154
Quantized Clear Recall Score: 92.3077


SKLEARN PREDICTION:
 [0 1 3 4 0 4 0 1 0 0 4 1 0]
QUANTIZED CLEAR PREDICTION:
 [0 1 3 4 0 4 0 1 0 1 4 1 0]
ACTUAL:
 [0 4 3 4 0 4 0 1 0 1 4 1 0]


In [ ]:
# Random Forest FHE Model
start_time = time.time()
fhe = quant.compile(x)
print(f"Running time for FHE compilation is {time.time() - start_time} seconds")
start_time = time.time()
y_pred_fhe = quant.predict(X_test, fhe='execute')
print(f"Running time for FHE prediction is {time.time() - start_time} seconds")

# Results for FHE Models

print("FHE Random Forest Results \n")
# Accuracy
fhe_accuracy = accuracy_score(y_test, y_pred_fhe) * 100
print(f"Accuracy: {fhe_accuracy:.4f}")
# Balanced Accuracy
fhe_bal_accuracy = balanced_accuracy_score(y_test, y_pred_fhe) * 100
print(f"Balanced accuracy: {fhe_bal_accuracy:.4f}")
# F1 Score
fhe_f1 = f1_score(y_test, y_pred_fhe, average='weighted') * 100
print(f"F1 Score: {fhe_f1:.4f}")
# Recall / Sensitivity Score
fhe_recall = recall_score(y_test, y_pred_fhe, average='weighted') * 100
print(f"FHE Recall Score: {fhe_recall:.4f}")

print("\n")
print("SKLEARN PREDICTION:\n", y_pred_clear)
print("QUANTIZED CLEAR PREDICTION:\n", y_pred_q)
print("FHE PREDICTION:\n", y_pred_fhe)
print("ACTUAL:\n", y_test)

print("\n")
print(f"Quantized vs FHE Comparison: {int((y_pred_fhe == y_pred_q).sum()/len(y_pred_fhe)*100)}% similar")
print(f"Sklearn vs FHE Comparison: {int((y_pred_fhe == y_pred_clear).sum()/len(y_pred_fhe)*100)}% similar")



Running time for FHE compilation is 0.842620849609375 seconds
Running time for FHE prediction is 2008.727369070053 seconds
FHE Random Forest Results 

Accuracy: 92.3077
Balanced accuracy: 93.7500
F1 Score: 92.3077
FHE Recall Score: 92.3077


SKLEARN PREDICTION:
 [0 1 3 4 0 4 0 1 0 0 4 1 0]
QUANTIZED CLEAR PREDICTION:
 [0 1 3 4 0 4 0 1 0 1 4 1 0]
FHE PREDICTION:
 [0 1 3 4 0 4 0 1 0 1 4 1 0]
ACTUAL:
 [0 4 3 4 0 4 0 1 0 1 4 1 0]


Quantized vs FHE Comparison: 100% similar
Sklearn vs FHE Comparison: 92% similar


In [ ]:
y_pred_clear_prob = skmodel.predict_proba(X_test)
sk_cond =  np.linalg.cond(y_pred_clear_prob)
print("Condition number of the sklearn test set:")
print(sk_cond)

y_pred_q_prob = quant.predict_proba(X_test)
quant_cond =  np.linalg.cond(y_pred_q_prob)
print("\nCondition number of the quantized test set:")
print(quant_cond)

Condition number of the sklearn test set:
27.175936217689582

Condition number of the quantized test set:
65.29924425398997


In [ ]:
y_pred_fhe_prob = quant.predict_proba(X_test, fhe='execute')
fhe_cond =  np.linalg.cond(y_pred_fhe_prob)
print("\nCondition number of the fhe test set:")
print(fhe_cond)


Condition number of the fhe test set:
65.29924425399001
